version: '3'

services:
    proxy: 
        image: nginx:1.13
        ports: 
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    web:
        image: httpd